var mainWindow = api.ui().mainWindow();
api.changeWindow(mainWindow);
var prop = api.ui().propertyRect("Расстояние");
var propertyEditor = api.ui().propertyEditor();
api.cursor().moveToRect(prop, 500);
api.cursor().leftButtonPress(propertyEditor);
var prop = api.ui().propertyRect("Расстояние");
var propertyEditor = api.ui().propertyEditor();
api.wait(100);
api.cursor().leftButtonRelease(propertyEditor);
api.keyboard().type("10", 500);
